In [14]:
import sympy as smp


x = smp.symbols('x')

A, B, C, D, E = smp.symbols('A, B, C, D, E')



lhs = (x**2 -1)/((x**2+1)**2 * (x+3))

rhs = (A*x + B)/(x**2+1) + (C*x+D)/(x**2+1)**2  + E/(x+3)


Equation = smp.Eq(lhs, rhs)

print(smp.solve(Equation, A, B, C, D, E))
Equation

{A: -2/25, B: 6/25, C: 1/5, D: -3/5, E: 2/25}


Eq((x**2 - 1)/((x + 3)*(x**2 + 1)**2), E/(x + 3) + (A*x + B)/(x**2 + 1) + (C*x + D)/(x**2 + 1)**2)

In [54]:
operator = {'OR', 'AND'}

zdanie = [-1, 1]


for a1 in zdanie:
    for a2 in zdanie:
        for sym in operator:
            print(f"{a1} {sym} {a2}")

-1 AND -1
-1 OR -1
-1 AND 1
-1 OR 1
1 AND -1
1 OR -1
1 AND 1
1 OR 1


In [2]:
import numpy as  np


array = np.array([1,1,1,1,1,2,2,2, 1,2,3,3, 1,2,3,4]).reshape(4,4)


print(np.linalg.inv(array))

[[ 2. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0. -1.  1.]]
