In [44]:
import numpy as np

def Determinant(Matrix:np.ndarray):
    assert type(Matrix) == np.ndarray, "Im sorry but you can't compute the determinant of a non-ndarray argument"
    assert Matrix.shape[0] == Matrix.shape[1], "You get only calculate the determinant for square matrices!"



    if Matrix.shape[0] == 1:
        return Matrix[0,0]
    
    det = 0
    
    for i in range(0,Matrix.shape[0]):
        minor =  Determinant(np.delete(np.delete(Matrix, i, axis = 0), 0, axis = 1))
        det += Matrix[i,0]*(-1)**(0+i) * minor

    
    return det

    

def SolveLinearSystem(Eqs: np.ndarray, intercepts:np.ndarray):
    assert type(Eqs) == np.ndarray, "You should convert the Eqs datatype to numpy.ndarray"
    assert type(intercepts) == np.ndarray, "You should convert the Intercepts datatype to numpy.ndarray"

    assert Eqs.shape[1]==Eqs.shape[0], "The dimensions of the Eqs  need to match"
    assert intercepts.shape[0] == Eqs.shape[0] and intercepts.ndim == 1, "The dimensions of the Eqs  need to match"


    SystemDeterminant = Determinant(Eqs)


    if SystemDeterminant != 0:
        for i in range(Eqs.shape[0]):
            var_matrix = Eqs.copy()
            var_matrix[:, i] = intercepts


            solution = Determinant(var_matrix)/SystemDeterminant

            print(solution)










[[5 2 6]
 [3 1 0]
 [5 5 5]]
[0, 2, 3]
0.4
0.8
-0.6
